language: node_js
node_js:
  - 5.3.0
install:
  - npm install
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
script:
  - $CI_ACTION
after_success:
  - 'test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh'
env:
  global:
    - TEST_SUITE=unit
    - GH_REF: github.com/gasolin/webdeacon.git
    - secure: kXfo2CINfUCzIi7YfzKDQ4Ap5xcp0wRhiG28gIs9Yq2qatUBc2ITTL9NbPmEOdZSjjYmkd2wNjLQ+KMflElAPKrEUEXC9GSBD5mxlATOcDHZSQ4zi3bPklLd40Yv9AtPv22+3VEdyEyy8UbW9XOvNtl18FknCurmLxYku1KnFhgz8zioDdn4Qi82PHWD/K1eFkJX4ky93lQTpx19g5U06q6u5X7Xcw5B0yxBMlQUMMgLSVne0scvuugw/m8NtGhsYCdneVbldOqeGEHebfhf2G7kAEQDUW3NxSCvISNx/yjEGnZlT8CHEaKvNGpipHlnSvylIs2vwbeqRgp+PXRI2/VIXTwXPOl5/Gp9jvENovTp2MfS5CPxU5DkGcoD0otBmMLpC3DSDHPaYnrj13RCL/yAInZAJGft6uA2BYKEW8zMemiwBiMt8MhM006Cl4xfiaL1tqTOjGe6CuW+WSrYLsjwTG3joy51shJTKTBtBY8Opr8nqD2Rb+9fzoTI91nYYX7pLeQ0neVxOSePIYLAVGc21raQxVfOWhS9Dv2HxcNu1SphdkJuRXjmEsXcDVTIERcU2uekxtNNHEHDNrpNZn5n//3/WCrCwg13BusfIPxB8TlLJgfNxHiYmaLNyI8Pkohh6w/+pD0SROPQcctmBP/hEUNJEgPnmO80L8+y75Q=
  matrix:
    - 'CI_ACTION="npm test"'
