language: node_js

node_js:
  - '5.3.0'

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
  matrix:
    - CI_ACTION="npm test"
